### ISSUE TITLE
White screen issues when the game starts or exits

### ISSUE THREAD

**Issue by wheniseeyouagain** [ducalex/retro-go#213]
Hi, ducalex
When entering or exiting the game, the screen will flash a white screen once, and it will be especially glaring when in a dark environment. I'm not sure if this is a code issue, I hope you could optimize it, even if the screen backlight is turned off at the moment of the white screen, it will solve the problem, thanks.

It's extremely brief, just a fraction of a second, but it occurs every time, like this：

<img width="1146" height="323" alt="Image" src="https://github.com/user-attachments/assets/9729a048-7945-4bb2-bd70-f8063d2e558e" />

**Comment by ducalex** [comment]
Part of the issue is that we lose control of the GPIO controlling the backlight when the esp32 restarts (when starting a game) and it seems to be initialized as an input with a pull-up which partially lights up the backlight.

I might be able to change the code to disable the backligtht as soon as possible, but there will always be 50-200ms out of our control unfortunately...

That being said, retro-go is supposed to fill the screen with black before a reboot, so a truly white flash should only occur during a cold boot, not when starting a game. So maybe there's a bug still.

Can you tell me what device you're using?

**Comment by wheniseeyouagain** [comment]
My device uses the ESP32-S3-WROOM-1U N16R8, which can be regarded as similar to the ESP32-S3-DevKitC-1 development board. The firmware is compiled with IDF4.4.7. I hope this information will be useful to you.

**Comment by ducalex** [comment]
My main interest was knowing which target you're using when building, to know which backlight and lcd init code path is applicable to your issue.

I've pushed a change that could help: https://github.com/ducalex/retro-go/commit/ca3940d88fa710a99d45c15099e09c03600c904b

If it is insufficient, another thing you might want to try is add the following lines at the end of the function `platform_init` in `rg_system.c`:

```c
    #ifdef RG_GPIO_LCD_BCKL
        gpio_set_direction(RG_GPIO_LCD_BCKL, GPIO_MODE_OUTPUT);
        gpio_set_level(RG_GPIO_LCD_BCKL, 0);
    #endif
```

Which will disable the backlight as early as possible during boot, and only enable again at the very end of display initialization, when it's been fully initialized and filled with black.

**Comment by wheniseeyouagain** [comment]
I have made the following:

1.Modified only the ili9341.h and rg_display.c files.
2.Modified the ili9341.h, rg_display.c, and rg_system.c files simultaneously.
3.Modified only the rg_system.c file.

Unfortunately, none of them worked, and the white screen issue still persists. My build directory is for a ported new device, although my screen driver is ST7789, ili9341.h is still used.  so I think it should be equivalent to the esp32s3-devkit-c. The content of its config.h is as follows:

```
// REF: https://wiki.odroid.com/odroid_go/odroid_go

// Target definition
#define RG_TARGET_NAME             "Katarina"

// Storage
#define RG_STORAGE_SDSPI_HOST       SPI3_HOST
#define RG_STORAGE_SDSPI_SPEED      SDMMC_FREQ_DEFAULT
#define RG_STORAGE_ROOT             "/sd"

// Audio
#define RG_AUDIO_USE_INT_DAC        0   // 0 = Disable, 1 = GPIO25, 2 = GPIO26, 3 = Both
#define RG_AUDIO_USE_EXT_DAC        1   // 0 = Disable, 1 = Enable

// Video
#define RG_SCREEN_DRIVER            0   // 0 = ILI9341
#define RG_SCREEN_HOST              SPI2_HOST
#define RG_SCREEN_SPEED             SPI_MASTER_FREQ_40M // SPI_MASTER_FREQ_80M
#define RG_SCREEN_BACKLIGHT         1
#define RG_SCREEN_WIDTH             240
#define RG_SCREEN_HEIGHT            240
#define RG_SCREEN_ROTATE            0
#define RG_SCREEN_MARGIN_TOP        0
#define RG_SCREEN_MARGIN_BOTTOM     0
#define RG_SCREEN_MARGIN_LEFT       0
#define RG_SCREEN_MARGIN_RIGHT      0
#define RG_SCREEN_INIT()                                                                                     \
    ILI9341_CMD(0x3A, 0x05);                                                                                 \
    ILI9341_CMD(0xB2, 0x0C, 0x0C, 0x00, 0x33, 0x33);                                                         \
    ILI9341_CMD(0xB7, 0x35);                                                                                 \
    ILI9341_CMD(0xBB, 0x38);                                                                                 \
    ILI9341_CMD(0xC0, 0x2C);                                                                                 \
    ILI9341_CMD(0xC2, 0x01);                                                                                 \
    ILI9341_CMD(0xC3, 0x11);                                                                                 \
    ILI9341_CMD(0xC4, 0x20);                                                                                 \
    ILI9341_CMD(0xC6, 0x0F);                                                                                 \
    ILI9341_CMD(0xD0, 0xA4, 0xA1);                                                                           \
    ILI9341_CMD(0xE0, 0xD0, 0x00, 0x05, 0x0E, 0x15, 0x0D, 0x37, 0x43, 0x47, 0x09, 0x15, 0x12, 0x16, 0x19);   \
    ILI9341_CMD(0xE1, 0xD0, 0x00, 0x05, 0x0D, 0x0C, 0x06, 0x2D, 0x44, 0x40, 0x0E, 0x1C, 0x18, 0x16, 0x19);


// Input
// Refer to rg_input.h to see all available RG_KEY_* and RG_GAMEPAD_*_MAP types
#define RG_GAMEPAD_ADC1_MAP {\
}

#define RG_GAMEPAD_GPIO_MAP {\
    {RG_KEY_UP,     GPIO_NUM_38, GPIO_PULLUP_ONLY, 0},\
    {RG_KEY_RIGHT,  GPIO_NUM_14, GPIO_PULLUP_ONLY, 0},\
    {RG_KEY_DOWN,   GPIO_NUM_21, GPIO_PULLUP_ONLY, 0},\
    {RG_KEY_LEFT,   GPIO_NUM_39, GPIO_PULLUP_ONLY, 0},\
    {RG_KEY_SELECT, GPIO_NUM_18, GPIO_PULLUP_ONLY, 0},\
    {RG_KEY_START,  GPIO_NUM_17, GPIO_PULLUP_ONLY, 0},\
    {RG_KEY_MENU,   GPIO_NUM_4, GPIO_PULLUP_ONLY, 0},\
    {RG_KEY_OPTION, GPIO_NUM_2, GPIO_PULLUP_ONLY, 0},\
    {RG_KEY_A,      GPIO_NUM_16, GPIO_PULLUP_ONLY, 0},\
    {RG_KEY_B,      GPIO_NUM_8, GPIO_PULLUP_ONLY, 0},\
}

// Battery
#define RG_BATTERY_DRIVER           1
#define RG_BATTERY_ADC_UNIT         ADC_UNIT_1
#define RG_BATTERY_ADC_CHANNEL      ADC_CHANNEL_0
#define RG_BATTERY_CALC_PERCENT(raw) (((raw) * 2.f - 3500.f) / (4200.f - 3500.f) * 100.f)
#define RG_BATTERY_CALC_VOLTAGE(raw) ((raw) * 2.f * 0.001f)

// Status LED
#define RG_GPIO_LED                 GPIO_NUM_48

// SPI Display (back up working)
#define RG_GPIO_LCD_MISO            GPIO_NUM_NC
#define RG_GPIO_LCD_MOSI            GPIO_NUM_9
#define RG_GPIO_LCD_CLK             GPIO_NUM_10
#define RG_GPIO_LCD_CS              GPIO_NUM_3
#define RG_GPIO_LCD_DC              GPIO_NUM_12
#define RG_GPIO_LCD_BCKL            GPIO_NUM_13
#define RG_GPIO_LCD_RST             GPIO_NUM_11

// SD Card
#define RG_GPIO_SDSPI_MISO          GPIO_NUM_15
#define RG_GPIO_SDSPI_MOSI          GPIO_NUM_6
#define RG_GPIO_SDSPI_CLK           GPIO_NUM_7
#define RG_GPIO_SDSPI_CS            GPIO_NUM_5

// External I2S DAC
#define RG_GPIO_SND_I2S_BCK         GPIO_NUM_41
#define RG_GPIO_SND_I2S_WS          GPIO_NUM_42
#define RG_GPIO_SND_I2S_DATA        GPIO_NUM_40
```

**Comment by ducalex** [comment]
I'm not seeing anything wrong in your config. I'm not sure what more could be done from my end...

Maybe you can try filming the device when you start a game? Possibly with fixed exposure. Knowing the timing of the flash might give me more ideas.

I'm not sure if the screen goes white when hardware reset is asserted but maybe an external pullup on GPIO 11 could help?

Also make sure to use the dev branch. All the current and future attempt at improving are in this branch.

**Comment by rapha-tech** [comment]
I've tested your rg_scren_init() on my st7789 screen, not the exact same as yours since my colors were inverted. But i've also noticed the blinking. Whereas with my rg_screen_init() I haven't experienced any blinking. So I guess there is something in your rg_screen_init that is causing the issue but I'm not sure. I would of loved to help you out but I don't have a compatible display sadly !

**Comment by wheniseeyouagain** [comment]
As Rapa-tech suggested, the problem might lie with rg_screen_init(). Through repeated testing, I found that adjusting the timing within the lcd_init function in ili9341.h can extend the white screen duration. Conversely, even if I set the time to 1ms, there is still a white screen lasting at least 20ms.

ILI9341_CMD(0x11); // Exit Sleep
rg_usleep(10 * 1000); // Even if this is set to 1, there's still a 20ms white screen
ILI9341_CMD(0x29); // Display on

I can't upload a video here, so I've captured some video clips. I also noticed a phenomenon: a few milliseconds before the white screen appears, the screen brightness increases from the default to the maximum, and after the white screen, the brightness returns to the default.(the screenshot was taken when entering the game)

<img width="1486" height="778" alt="Image" src="https://github.com/user-attachments/assets/97e19458-614f-4efa-9a5b-06d1e4b0917e" />

Additionally, the screen driver code I'm using was provided by the seller, and I have no idea where the problem is. Please help me check it. @ducalex @rapha-tech 

[ST7789V2.txt](https://github.com/user-attachments/files/21459408/ST7789V2.txt)

**Comment by ducalex** [comment]
It seems like the flash occurs during the esp32 restart or maybe during the lcd reset (but the backlight should be off during the latter).

Can you try the following:

1. Add a `rg_usleep(1000 * 1000);` at the top of lcd_init in ili9341.h (currently line 204). Is the screen bright for an entire second?
2. Then move the `rg_usleep(1000 * 1000);` to just before `spi_init();` in lcd_init (currently line 221). Does the screen go dark for an entire second? And does the flash happens before that point?
3. If the flash doesn't happen before that point, keep lowering the `rg_usleep(1000 * 1000);` until you find where it happens.


Also the ST7789 seems to have some backlight control and also Content Adaptive Brightness Control that could make it vary gamma and backlight by itself, maybe that's something to look at. Although you don't issue the concerned commands (0x51 and 0x55), so I don't think it's related.

**Comment by wheniseeyouagain** [comment]
I also believe the screen flash occurs during the ESP32 restart, as I observed the same flash when powering on the device.

Here's what I did:

Added rg_usleep(1000 * 1000); at the top of the lcd_init function—this only extended the loading screen before the flash by one second, but the screen itself did not stay bright for the full second.

Moved rg_usleep(1000 * 1000); just before spi_init();—the screen stayed bright for a full second, but the flash still occurred afterward.

Gradually reducing the delay only shortened the bright period but did not make the flash happen earlier.

Then, I continued moving rg_usleep(1000 * 1000); further down:

When placed before ILI9341_CMD(0x10); (around line 243), the flash itself lasted for one second.

When moved further down, after ILI9341_CMD(0x29); (around line 255), the loading screen after the flash was extended by one second.

Summary:
When rg_usleep(1000 * 1000); is placed at any of the five marked positions inside the red box, it extends the duration of the flash. Otherwise, it extends the loading screen either before or after the flash. In other words, the flash occurs within the red box, starting at position 1 and ending at ILI9341_CMD(0x29);

<img width="684" height="832" alt="Image" src="https://github.com/user-attachments/assets/fdc1b502-d038-4b85-aaa2-7bb33d093f2a" />

**Comment by wheniseeyouagain** [comment]
Adding one more point: When I moved rg_usleep(1000 * 1000); to line 229 in the diagram, it immediately jumped to line 243, so I'm unsure whether placing it between lines 229 and 243 would extend the flash duration.

**Comment by ducalex** [comment]
Thanks, you've documented the issue well. What I don't understand is why the screen remains lit. It should be dark as of line 222, all the way to the end of the function.

Some causes:
- one of the ledc_* function fails or isn't currently setup correctly for your use case
- your RG_GPIO_LCD_BCKL is wrong
- your backlight is actually controlled by the ST7789 and not a PWM pin

Do you have control of the backlight in the options menu?

**Comment by ducalex** [comment]
At the top of lcd_init in the `#ifdef RG_GPIO_LCD_BCKL` block you can try two things.



The first is to check if the pin actually controls the backlight (replace the entire block with this):


```c
    // Initialize backlight at 0% to avoid the lcd reset flash
    gpio_set_direction(RG_GPIO_LCD_BCKL, GPIO_MODE_OUTPUT);
    gpio_set_level(RG_GPIO_LCD_BCKL, 0);
```

If this code does not turn off your backlight, then the pin is definitely incorrect and/or the LCD controller controls the backlight.


Assuming the above code did work, you can check for errors in the PWM driver init (again replace the entire block with this):
```c
    // Initialize backlight at 0% to avoid the lcd reset flash
    esp_err_t a, b, c;
    a = ledc_timer_config(&(ledc_timer_config_t){
        .duty_resolution = LEDC_TIMER_13_BIT,
        .freq_hz = 5000,
        .speed_mode = LEDC_LOW_SPEED_MODE,
        .timer_num = LEDC_TIMER_0,
    });
    b = ledc_channel_config(&(ledc_channel_config_t){
        .channel = LEDC_CHANNEL_0,
        .duty = 0,
        .gpio_num = RG_GPIO_LCD_BCKL,
        .speed_mode = LEDC_LOW_SPEED_MODE,
        .timer_sel = LEDC_TIMER_0,
    });
    c = ledc_fade_func_install(0);
    RG_LOGW("ledc result: 0x%03X, 0x%03X, 0x%03X", a, b, c);
```

Any non 0x000 result indicates an error.

**Comment by wheniseeyouagain** [comment]
> Thanks, you've documented the issue well. What I don't understand is why the screen remains lit. It should be dark as of line 222, all the way to the end of the function.
> 
> Some causes:
> 
> * one of the ledc_* function fails or isn't currently setup correctly for your use case
> * your RG_GPIO_LCD_BCKL is wrong
> * your backlight is actually controlled by the ST7789 and not a PWM pin
> 
> Do you have control of the backlight in the options menu?

I did enable the backlight setting in the menu, and it works. However, I once encountered an issue: the backlight adjustment was inverted from the actual effect (the larger the number, the darker the screen, and the smaller the number, the brighter the screen).

Therefore, in the rg_display_set_backlight function in the rg_display.c file, I modified `lcd_set_backlight(config.backlight);` to `lcd_set_backlight(RG_DISPLAY_BACKLIGHT_MAX - config.backlight);`, which made the brightness adjustment work normally.

<img width="932" height="191" alt="Image" src="https://github.com/user-attachments/assets/660de489-2874-492d-a924-21493685fdf9" />

At the same time, I also added `lcd_set_backlight(RG_DISPLAY_BACKLIGHT_MAX - config.backlight);` after `lcd_init();` in the rg_display_init function to remember the brightness value.

<img width="790" height="411" alt="Image" src="https://github.com/user-attachments/assets/8dc1c52d-3dd8-4706-a195-d0afd9dfe9ad" />

I have tried reverting these modifications, but the screen flickering still occurs.

**Comment by wheniseeyouagain** [comment]
> At the top of lcd_init in the `#ifdef RG_GPIO_LCD_BCKL` block you can try two things.
> 
> The first is to check if the pin actually controls the backlight (replace the entire block with this):
> 
>     // Initialize backlight at 0% to avoid the lcd reset flash
>     gpio_set_direction(RG_GPIO_LCD_BCKL, GPIO_MODE_OUTPUT);
>     gpio_set_level(RG_GPIO_LCD_BCKL, 0);
> If this code does not turn off your backlight, then the pin is definitely incorrect and/or the LCD controller controls the backlight.
> 
> Assuming the above code did work, you can check for errors in the PWM driver init (again replace the entire block with this):
> 
>     // Initialize backlight at 0% to avoid the lcd reset flash
>     esp_err_t a, b, c;
>     a = ledc_timer_config(&(ledc_timer_config_t){
>         .duty_resolution = LEDC_TIMER_13_BIT,
>         .freq_hz = 5000,
>         .speed_mode = LEDC_LOW_SPEED_MODE,
>         .timer_num = LEDC_TIMER_0,
>     });
>     b = ledc_channel_config(&(ledc_channel_config_t){
>         .channel = LEDC_CHANNEL_0,
>         .duty = 0,
>         .gpio_num = RG_GPIO_LCD_BCKL,
>         .speed_mode = LEDC_LOW_SPEED_MODE,
>         .timer_sel = LEDC_TIMER_0,
>     });
>     c = ledc_fade_func_install(0);
>     RG_LOGW("ledc result: 0x%03X, 0x%03X, 0x%03X", a, b, c);
> Any non 0x000 result indicates an error.

Okay, I'll test these two methods later and then let you know the results.

**Comment by wheniseeyouagain** [comment]
After verification, the code:
gpio_set_direction(RG_GPIO_LCD_BCKL, GPIO_MODE_OUTPUT);
gpio_set_level(RG_GPIO_LCD_BCKL, 0);
cannot turn off the backlight, and the screen brightness adjustment also becomes ineffective. Additionally, when the device is powered on, there will be a period of garbled screen display, like this:

<img width="200" height="211" alt="Image" src="https://github.com/user-attachments/assets/8359387e-706d-457d-bb2a-22db127aabe9" />

**Comment by ducalex** [comment]
> I did enable the backlight setting in the menu, and it works. However, I once encountered an issue: the backlight adjustment was inverted from the actual effect (the larger the number, the darker the screen, and the smaller the number, the brighter the screen).


In lcd_init there's a line `.duty = 0,` that sets the backlight to "0". Change it for `.duty = 0x1FFF,`. This should result in the backlight being off during init, making the init flash invisible.



Alternatively in the ledc_channel_config_t struct there is also a output_invert flag that you could try, add this line right after the duty line: `.flags.output_invert = 1,` (if it works you will have to undo your other modifications to maintain control through the menu)

**Comment by wheniseeyouagain** [comment]
That's amazing! It worked!!! Now there's no more screen flickering when entering or exiting games!  

Thank you so much. You've been helping me with this issue for nearly a month, and I always believed you could help me solve it because you're so skilled. I can't find another way to express my gratitude, so I just want to say thank you again!  

Now that the problem is resolved, you can close this issue after reading this message.

**Comment by ducalex** [comment]
That's good news!

Can you tell me which method worked for you? The `flags.output_invert = 1` or the manual inversion of duty? I would like to add a config option in case someone else encounters the same issue in the future.

**Comment by wheniseeyouagain** [comment]
Both methods worked, but I would recommend using the flags.output_invert = 1; This way, there’s no need to add code like lcd_set_backlight(RG_DISPLAY_BACKLIGHT_MAX - config.backlight); in the rg_display.c file, making the code cleaner and more consistent.

**Comment by ducalex** [comment]
Thanks for the reply. I've added `RG_GPIO_LCD_BCKL_INVERT`, when defined it will add the output_invert flag.

I've also added `RG_GPIO_LED_INVERT` to invert the main LED (#149).

I'm not sure I'm happy with the naming, maybe I'll rename them. to INVERTED or ACTIVE_LOW. Or maybe not, it really doesn't matter in the end I guess 🤷‍♀️
